### PR TITLE
We Can Port It in vectors

### PR DESCRIPTION
**Pull request by hroncok**
E.g. for posters :)

### CODE REVIEW

**Comment by torsava** [comment]
Cool, thanks!! :)

**Comment by hroncok** [comment]
Now google some reasonable poster printer and get some on A0 to hang it in
the office :D

**Comment by torsava** [comment]
Hehe. I'm not sure how Petr would feel about that :D Also, can we expense it? :D

**Comment by hroncok** [comment]
I don't think so :)

**Comment by torsava** [comment]
Oh well, let's start a collection :D

**Pull request merged**
